### ISSUE TITLE
Self-hosted Compiler

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#1356]
It would be cool to get Natalie able to self-host again. Specifically, running this should work (albeit slowly):

```
bin/natalie bin/natalie -e "puts 'hello world'"
```

This is a tracking issue as I find things that need to be fixed. This list will likely grow.

- [x] `FFI` library - #1315
- [ ] ~`Method#parameters` (needed [here](https://github.com/ruby/prism/blob/main/templates/lib/prism/serialize.rb.erb#L4))~ Punting here: #1385
- [x] `String#scan` (needed [here](https://github.com/ruby/prism/blob/main/lib/prism/parse_result.rb#L35)) - #1359
- [x] `Dir#[]` (needed [here](https://github.com/natalie-lang/natalie/blob/master/lib/natalie/compiler/backends/cpp_backend.rb#L103)) - #1376 
- [x] `Kernel#spawn` should accept `env` hash (needed [here](https://github.com/natalie-lang/natalie/blob/master/bin/natalie#L227)) - #1383
- [x] Fix bug with self-hosted compiler not initializing objects, e.g. `init_array(env, self)` and `init_comparable(env, self)`

**Comment by seven1m** [comment]
This is done! We can now run:

```sh
bin/natalie bin/natalie -e "puts 'hello world'"
```

...or:

```sh
bin/natalie -c bin/nat bin/natalie

bin/nat --version
Natalie 0.1

bin/nat -e "puts 'hi'"
hi
```

There are bugs of course, and I will be working to get this running through CI so we don't break it again in the future.
